@host=http://localhost:8080
###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Narancslé",
  "size": "1L",
  "departmentId": 3,
  "position": "LEFT",
  "storeId": 3,
  "price": 599.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Kutyaeledel",
  "size": "2kg",
  "departmentId": 4,
  "position": "RIGHT",
  "storeId": 3,
  "price": 2499.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Sampon",
  "size": "400ml",
  "departmentId": 5,
  "position": "TOP",
  "storeId": 3,
  "price": 1299.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Toalettpapír",
  "size": "8db",
  "departmentId": 6,
  "position": "BOTTOM",
  "storeId": 3,
  "price": 1799.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Mentolos cukorka",
  "size": "100g",
  "departmentId": 7,
  "position": "LEFT",
  "storeId": 3,
  "price": 499.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Kifli",
  "size": "1db",
  "departmentId": 8,
  "position": "RIGHT",
  "storeId": 3,
  "price": 89.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Burgonyachips",
  "size": "150g",
  "departmentId": 9,
  "position": "TOP",
  "storeId": 3,
  "price": 799.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Őrölt kávé",
  "size": "250g",
  "departmentId": 10,
  "position": "BOTTOM",
  "storeId": 3,
  "price": 1499.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Társasjáték",
  "size": "1db",
  "departmentId": 11,
  "position": "LEFT",
  "storeId": 3,
  "price": 5999.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Fekete bors",
  "size": "50g",
  "departmentId": 12,
  "position": "RIGHT",
  "storeId": 3,
  "price": 699.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Paradicsomszósz",
  "size": "500ml",
  "departmentId": 13,
  "position": "TOP",
  "storeId": 3,
  "price": 899.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Csokoládé",
  "size": "100g",
  "departmentId": 14,
  "position": "BOTTOM",
  "storeId": 3,
  "price": 549.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Konzerv kukorica",
  "size": "340g",
  "departmentId": 15,
  "position": "LEFT",
  "storeId": 3,
  "price": 599.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Liszt",
  "size": "1kg",
  "departmentId": 16,
  "position": "RIGHT",
  "storeId": 3,
  "price": 499.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Spagetti",
  "size": "500g",
  "departmentId": 17,
  "position": "TOP",
  "storeId": 3,
  "price": 699.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Joghurt",
  "size": "150g",
  "departmentId": 18,
  "position": "BOTTOM",
  "storeId": 3,
  "price": 349.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Mosogatószer",
  "size": "500ml",
  "departmentId": 19,
  "position": "LEFT",
  "storeId": 3,
  "price": 999.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Vörösbor",
  "size": "0.75L",
  "departmentId": 20,
  "position": "RIGHT",
  "storeId": 3,
  "price": 2499.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Világos sör",
  "size": "0.5L",
  "departmentId": 21,
  "position": "TOP",
  "storeId": 3,
  "price": 499.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Whisky",
  "size": "0.7L",
  "departmentId": 22,
  "position": "BOTTOM",
  "storeId": 3,
  "price": 5999.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Szénsavmentes ásványvíz",
  "size": "1.5L",
  "departmentId": 23,
  "position": "LEFT",
  "storeId": 3,
  "price": 199.99
}
###
POST {{host}}/products
Content-Type: application/json

{
"name": "Enyhe ásványvíz",
"size": "1.5L",
"departmentId": 23,
"position": "RIGHT",
"storeId": 3,
"price": 199.99
}

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Alufólia",
  "size": "20m",
  "departmentId": 24,
  "position": "RIGHT",
  "storeId": 3,
  "price": 799.99
}

###

POST {{host}}/products
Content-Type: application/json

{
  "name": "Folpakk",
  "size": "25m",
  "departmentId": 24,
  "position": "LEFT",
  "storeId": 3,
  "price": 799.99
}


###

###
POST {{host}}/products
Content-Type: application/json

{
  "name": "Kóla",
  "size": "2L",
  "departmentId": 3,
  "position": "LEFT",
  "storeId": 3,
  "price": 799.99
}

###
POST http://localhost:8080/shopping-lists
Authorization: Bearer eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJuYW1lIjoiVGVzdCBVc2VyIiwicGljdHVyZSI6IiIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdXRoX3RpbWUiOjE3ODAzNTY0MTUsInVzZXJfaWQiOiJya1pmNGZ1U2kyU2FMVFRwdW9GVDJ1SnN5b0tYIiwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QHRlc3QuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifSwiaWF0IjoxNzgwMzU2NDE1LCJleHAiOjE3ODAzNjAwMTUsImF1ZCI6InNob3BtYXAtMWFmY2EiLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc2hvcG1hcC0xYWZjYSIsInN1YiI6InJrWmY0ZnVTaTJTYUxUVHB1b0ZUMnVKc3lvS1gifQ.
Content-Type: application/json

{
  "name": "Teljes bolti teszt",
  "items": [
    {
      "shoppingItemName": "Narancslé",
      "attributes": "1L"
    },
    {
      "shoppingItemName": "Kifli",
      "attributes": "1db"
    },
    {
      "shoppingItemName": "Spagetti",
      "attributes": "500g"
    },
    {
      "shoppingItemName": "Joghurt",
      "attributes": "150g"
    },
    {
      "shoppingItemName": "Mosogatószer",
      "attributes": "500ml"
    },
    {
      "shoppingItemName": "Szénsavmentes ásványvíz",
      "attributes": "1.5L"
    }
  ]
}


###

GET http://localhost:8080/store/3/shopping-lists/4/matches

###

###
POST {{host}}/calculate-route
Content-Type: application/json

{
  "mapId": 3,
  "products": [
    {
      "articleNo": 4,
      "departmentId": 3,
      "position": "LEFT"
    },
    {
      "articleNo": 9,
      "departmentId": 8,
      "position": "RIGHT"
    },
    {
      "articleNo": 18,
      "departmentId": 17,
      "position": "TOP"
    },
    {
      "articleNo": 19,
      "departmentId": 18,
      "position": "BOTTOM"
    },
    {
      "articleNo": 20,
      "departmentId": 19,
      "position": "LEFT"
    },
    {
      "articleNo": 24,
      "departmentId": 23,
      "position": "LEFT"
    }



  ]
}
###
POST {{host}}/store
Content-Type: application/json

{
  "name": "Navigate Test Shop Reopening",
  "location": "Navigateland, Algo st. 1-3, 1234"
}


###
POST {{host}}/maps
Content-Type: application/json

{
  "width": 80,
  "height": 70,
  "entranceX": 0.0,
  "entranceY": 40,
  "exitX": 70,
  "exitY": 40,
  "storeId": 4
}

###
POST {{host}}/tills
Content-Type: application/json

{
  "mapId": 4,
  "startX": 20,
  "startY": 60,
  "width": 40,
  "height": 5
}




###
POST {{host}}/departments
Content-Type: application/json

{
  "mapId": 4,
  "name": "Tejtermék",
  "startX": 8.0,
  "startY": 8.0,
  "width": 5.0,
  "height": 5.0
}

###
POST {{host}}/departments
Content-Type: application/json

{
"mapId": 4,
"name": "Pékáru",
"startX": 60.0,
"startY": 10.0,
"width": 6.0,
"height": 40
}

###
POST {{host}}/departments
Content-Type: application/json

{
  "mapId": 4,
  "name": "Zöldség és gyümölcs",
  "startX": 15.0,
  "startY": 20.0,
  "width": 20.0,
  "height": 15.0
}

###
POST {{host}}/departments
Content-Type: application/json

{
  "mapId": 4,
  "name": "Hús",
  "startX": 30.0,
  "startY": 40.0,
  "width": 10.0,
  "height": 10.0
}

###

POST {{host}}/departments
Content-Type: application/json

{
  "mapId": 4,
  "name": "Társasjáték",
  "startX": 37.0,
  "startY": 30.0,
  "width": 5.0,
  "height": 6.0
}

###

POST {{host}}/departments
Content-Type: application/json

{
  "mapId": 4,
  "name": "Fagyasztott élelmiszer",
  "startX": 45.0,
  "startY": 50.0,
  "width": 10.0,
  "height": 5.0
}

###
POST {{host}}/departments
Content-Type: application/json

{
  "mapId": 4,
  "name": "Kávé és Tea",
  "startX": 45,
  "startY": 25,
  "width": 10,
  "height": 20
}


###

POST {{host}}/products
Content-Type: application/json

{
  "name": "Tej",
  "size": "20m",
  "departmentId": 27,
  "position": "RIGHT",
  "storeId": 4,
  "price": 799.99
}
###
POST {{host}}/products
Content-Type: application/json

{
"name": "Társasjáték",
"size": "20m",
"departmentId": 33,
"position": "TOP",
"storeId": 4,
"price": 799.99
}

###

POST {{host}}/products
Content-Type: application/json

{
  "name": "Kenyér",
  "size": "20m",
  "departmentId": 28,
  "position": "RIGHT",
  "storeId": 4,
  "price": 799.99
}

###

POST {{host}}/products
Content-Type: application/json

{
  "name": "Alma",
  "size": "20m",
  "departmentId": 29,
  "position": "LEFT",
  "storeId": 4,
  "price": 799.99
}

###

POST {{host}}/products
Content-Type: application/json

{
  "name": "Csirkemell",
  "size": "20m",
  "departmentId": 30,
  "position": "RIGHT",
  "storeId": 4,
  "price": 799.99
}

###

POST {{host}}/products
Content-Type: application/json

{
  "name": "Hátszín",
  "size": "20m",
  "departmentId": 30,
  "position": "LEFT",
  "storeId": 4,
  "price": 799.99
}

###

POST {{host}}/products
Content-Type: application/json

{
  "name": "Halrudacska",
  "size": "20m",
  "departmentId": 31,
  "position": "TOP",
  "storeId": 4,
  "price": 799.99
}

###

POST {{host}}/products
Content-Type: application/json

{
  "name": "Kávé",
  "size": "20m",
  "departmentId": 32,
  "position": "BOTTOM",
  "storeId": 4,
  "price": 799.99
}

###

POST {{host}}/products
Content-Type: application/json

{
  "name": "Zsemle",
  "size": "20m",
  "departmentId": 30,
  "position": "TOP",
  "storeId": 4,
  "price": 799.99
}
###
POST {{host}}/products
Content-Type: application/json

{
"name": "Steak",
"size": "20m",
"departmentId": 28,
"position": "TOP",
"storeId": 4,
"price": 799.99
}

###
POST {{host}}/calculate-route
Content-Type: application/json

{
  "mapId": 4,
  "products": [
    {
      "articleNo": 31,
      "departmentId": 29,
      "position": "LEFT"
    },
    {
      "articleNo": 29,
      "departmentId": 27,
      "position": "RIGHT"
    },
    {
      "articleNo": 34,
      "departmentId": 31,
      "position": "TOP"
    },
    {
      "articleNo": 38,
      "departmentId": 33,
      "position": "TOP"
    },
    {
      "articleNo": 35,
      "departmentId": 32,
      "position": "BOTTOM"
    },
    {
      "articleNo": 32,
      "departmentId": 30,
      "position": "RIGHT"
    },
    {
      "articleNo": 30,
      "departmentId": 28,
      "position": "RIGHT"
    },
    {
      "articleNo": 33,
      "departmentId": 30,
      "position": "LEFT"
    },
    {
      "articleNo": 36,
      "departmentId": 30,
      "position": "TOP"
    },
    {
      "articleNo": 37,
      "departmentId": 28,
      "position": "TOP"
    }





  ]
}

###

{
      "articleNo": 15,
      "departmentId": 14,
      "position": "BOTTOM"
    },
    {
      "articleNo": 5,
      "departmentId": 4,
      "position": "RIGHT"
    },
    {
      "articleNo": 12,
      "departmentId": 11,
      "position": "LEFT"
    },
    {
      "articleNo": 10,
      "departmentId": 9,
      "position": "TOP"
    }
,
{
      "articleNo": 14,
      "departmentId": 13,
      "position": "TOP"
    },
    {
      "articleNo": 17,
      "departmentId": 16,
      "position": "RIGHT"
    },
    {
      "articleNo": 11,
      "departmentId": 10,
      "position": "BOTTOM"
    },
    {
      "articleNo": 13,
"departmentId": 12,
"position": "RIGHT"
}

{
      "articleNo": 6,
      "departmentId": 5,
      "position": "TOP"
    },
    {
      "articleNo": 7,
      "departmentId": 6,
      "position": "BOTTOM"
    },
    {
      "articleNo": 8,
      "departmentId": 7,
      "position": "LEFT"
    },
    {
      "articleNo": 16,
      "departmentId": 15,
      "position": "LEFT"
    }
,
{
      "articleNo": 21,
      "departmentId": 20,
      "position": "RIGHT"
    },
    {
      "articleNo": 22,
      "departmentId": 21,
      "position": "TOP"
    },
    {
      "articleNo": 23,
      "departmentId": 22,
      "position": "BOTTOM"
    },
     {
      "articleNo": 25,
"departmentId": 24,
"position": "RIGHT"
}


{
      "articleNo": 27,
      "departmentId": 24,
      "position": "LEFT"
    },
    {
      "articleNo": 28,
      "departmentId": 23,
      "position": "RIGHT"
    }

###

POST {{host}}/departments
Content-Type: application/json

{
  "mapId": 3,
  "name": "ERINTI_DE_NEM_METSZI",
  "startX": 21.0,
  "startY": 90.0,
  "width": 17.5,
  "height": 30.0
}

###
POST {{host}}/departments
Content-Type: application/json

{
  "mapId": 3,
  "name": "BFS_FALTESZT",
  "startX": 0,
  "startY": 211,
  "width": 215.5,
  "height": 1
}

###
DELETE {{host}}/departments/26


####

POST {{host}}/store
Content-Type: application/json

{
  "name": "Navigate Test Shop Reopening",
  "location": "Navigateland, Algo st. 1-3, 1234"
}