type Product @table(name: "Products", singular: "product", plural: "products", key: ["id"]) {
  id: UUID! @col(name: "product_id") @default(expr: "uuidV4()")
  name: String! @col(name: "name")
  size: Int @col(name: "size")
  shelf: Shelf! @ref
  price: Int @col(name: "price")
}

# Shelf Entity
type Shelf @table(name: "Shelves", singular: "shelf", plural: "shelves", key: ["id"]) {
  id: UUID! @col(name: "shelf_id") @default(expr: "uuidV4()")
  department: Department! @ref
  width: Int @col(name: "width")
  height: Int @col(name: "height")
  startX: Int @col(name: "start_x")
  startY: Int @col(name: "start_y")
}

# Store Entity
type Store @table(name: "Stores", singular: "store", plural: "stores", key: ["id"]) {
  id: UUID! @col(name: "store_id") @default(expr: "uuidV4()")
  name: String! @col(name: "name")
  location: String! @col(name: "location")


}

# Department Entity
type Department @table(name: "Departments", singular: "department", plural: "departments", key: ["id"]) {
  id: UUID! @col(name: "department_id") @default(expr: "uuidV4()")
  map: Map! @ref
  type: String @col(name: "type")
  name: String! @col(name: "name")
  width: Int @col(name: "width")
  height: Int @col(name: "height")
  startX: Int @col(name: "start_x")
  startY: Int @col(name: "start_y")
  
}

# Map Entity
type Map @table(name: "Maps", singular: "map", plural: "maps", key: ["id"]) {
  id: UUID! @col(name: "map_id") @default(expr: "uuidV4()")
  store: Store! @ref
  width: Int @col(name: "width")
  height: Int @col(name: "height")
  entranceX: Int @col(name: "entrance_x")
  entranceY: Int @col(name: "entrance_y")
  exitX: Int @col(name: "exit_x")
  exitY: Int @col(name: "exit_y")
 

}

# WallBlock Entity
type WallBlock @table(name: "WallBlocks", singular: "wall_block", plural: "wall_blocks", key: ["id"]) {
  id: UUID! @col(name: "wall_block_id") @default(expr: "uuidV4()")
  map: Map! @ref
  width: Int @col(name: "width")
  height: Int @col(name: "height")
  startX: Int @col(name: "start_x")
  startY: Int @col(name: "start_y")
}

# Till Entity
type Till @table(name: "Tills", singular: "till", plural: "tills", key: ["id"]) {
  id: UUID! @col(name: "till_id") @default(expr: "uuidV4()")
  map: Map! @ref
  width: Int @col(name: "width")
  height: Int @col(name: "height")
  startX: Int @col(name: "start_x")
  startY: Int @col(name: "start_y")
}

# Root Query


